run:
  timeout: 5m
  modules-download-mode: readonly
  allow-parallel-runners: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - revive
    - misspell
    - prealloc
    - unconvert
    - unparam
    - whitespace

linters-settings:
  goimports:
    local-prefixes: gossip-chat

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
  max-issues-per-linter: 0
  max-same-issues: 0